export const GET_ERRORS = "GET_ERRORS";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CODE_SNIPPET = "SET_CODE_SNIPPET";
export const SET_USER_VISIT_COUNT = "SET_USER_VISIT_COUNT";
